# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ABOUT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ABOUT(object):
    def setupUi(self, ABOUT):
        ABOUT.setObjectName("ABOUT")
        ABOUT.resize(665, 491)
        self.label_2 = QtWidgets.QLabel(ABOUT)
        self.label_2.setGeometry(QtCore.QRect(100, 420, 421, 31))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(ABOUT)
        self.widget.setGeometry(QtCore.QRect(100, 80, 441, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ABOUT)
        QtCore.QMetaObject.connectSlotsByName(ABOUT)

    def retranslateUi(self, ABOUT):
        _translate = QtCore.QCoreApplication.translate
        ABOUT.setWindowTitle(_translate("ABOUT", "ABOUT"))
        self.label_2.setText(_translate("ABOUT", "<html><head/><body><p><span style=\" font-size:20pt; font-style:italic;\">Tüm hakları saklıdır © 2021</span></p></body></html>"))
        self.label_5.setText(_translate("ABOUT", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#aa0000;\">GÜVENLİK:</span></p></body></html>"))
        self.label_4.setText(_translate("ABOUT", "<html><head/><body><p><span style=\" font-size:12pt;\">➜Program kullanımı esnasında herhangi bir veri depolaması yapılmamaktadır. </span></p><p><span style=\" font-size:12pt;\">➜Güvenli bir şekilde hesaplarınıza giriş yapabilirsiniz.</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("ABOUT", "<html><head/><body><p><span style=\" font-size:12pt;\">MEVCUT VERSİYON :</span></p></body></html>"))
        self.label_3.setText(_translate("ABOUT", "<html><head/><body><p><span style=\" font-size:12pt;\">21.1.1</span></p></body></html>"))


