# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INTERFACEAPP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 855)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 30, 291, 151))
        self.label_3.setStyleSheet("image: url(:/newimage/d2e53ea31ec15e6a8129008563713de5.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 521, 401, 291))
        self.listWidget.setObjectName("listWidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 480, 321, 41))
        self.label_4.setObjectName("label_4")
        self.LOGINBUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LOGINBUTTON.setGeometry(QtCore.QRect(660, 430, 111, 41))
        self.LOGINBUTTON.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d2e53ea31ec15e6a8129008563713de5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGINBUTTON.setIcon(icon)
        self.LOGINBUTTON.setObjectName("LOGINBUTTON")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(730, 200, 41, 21))
        self.toolButton.setObjectName("toolButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 470, 1031, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(270, 230, 501, 191))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.USERNAMELABEL = QtWidgets.QLabel(self.layoutWidget)
        self.USERNAMELABEL.setObjectName("USERNAMELABEL")
        self.verticalLayout.addWidget(self.USERNAMELABEL)
        self.USERNAMEIN = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.USERNAMEIN.sizePolicy().hasHeightForWidth())
        self.USERNAMEIN.setSizePolicy(sizePolicy)
        self.USERNAMEIN.setObjectName("USERNAMEIN")
        self.verticalLayout.addWidget(self.USERNAMEIN)
        self.PASSWORDLABEL = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PASSWORDLABEL.sizePolicy().hasHeightForWidth())
        self.PASSWORDLABEL.setSizePolicy(sizePolicy)
        self.PASSWORDLABEL.setObjectName("PASSWORDLABEL")
        self.verticalLayout.addWidget(self.PASSWORDLABEL)
        self.PASSWORDIN = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PASSWORDIN.sizePolicy().hasHeightForWidth())
        self.PASSWORDIN.setSizePolicy(sizePolicy)
        self.PASSWORDIN.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PASSWORDIN.setObjectName("PASSWORDIN")
        self.verticalLayout.addWidget(self.PASSWORDIN)
        self.SHOWITEM = QtWidgets.QPushButton(self.centralwidget)
        self.SHOWITEM.setGeometry(QtCore.QRect(440, 660, 111, 31))
        self.SHOWITEM.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-color: rgb(255, 85, 0);")
        self.SHOWITEM.setObjectName("SHOWITEM")
        self.LOGOUT = QtWidgets.QPushButton(self.centralwidget)
        self.LOGOUT.setGeometry(QtCore.QRect(440, 700, 111, 31))
        self.LOGOUT.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 170, 255);")
        self.LOGOUT.setObjectName("LOGOUT")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 500, 371, 101))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionABOUT = QtWidgets.QAction(MainWindow)
        self.actionABOUT.setObjectName("actionABOUT")
        self.actionCONTACT = QtWidgets.QAction(MainWindow)
        self.actionCONTACT.setObjectName("actionCONTACT")
        self.menuHelp.addAction(self.actionABOUT)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INSTAGRAM ANALİZ"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">DON\'T FOLLOW YOU BACK </span></p></body></html>"))
        self.LOGINBUTTON.setText(_translate("MainWindow", "LOGIN"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.USERNAMELABEL.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">USERNAME:</span></p></body></html>"))
        self.PASSWORDLABEL.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">PASSWORD:</span></p></body></html>"))
        self.SHOWITEM.setText(_translate("MainWindow", "GÖRÜNTÜLE"))
        self.LOGOUT.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">GÖRÜNTÜLEMEK İSTEDİĞİNİZ HESABI SEÇİP AŞAĞIDAKİ \'GÖRÜNTÜLE\' BUTONUNA BASINIZ.</span></p></body></html>"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionABOUT.setText(_translate("MainWindow", "ABOUT..."))
        self.actionCONTACT.setText(_translate("MainWindow", "CONTACT"))
import TEST


